[package]
name = "eternum"
version = "0.1.0"

[scripts]

[dependencies]
dojo_core = { path = "/Users/aymericdelabrousse/Projects/blockchain/cairo/dojo_folder/dojo-aymeric/crates/dojo-core" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }


[[target.dojo]]
