kind = "DojoContract"
class_hash = "0x3bb8e4d0e2413d5ded2beed80fd6fadad96afb817f528a4fb73fa92544e232d"
original_class_hash = "0x3bb8e4d0e2413d5ded2beed80fd6fadad96afb817f528a4fb73fa92544e232d"
base_class_hash = "0x0"
abi = "manifests/prod/abis/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::transport::contracts::road_systems::road_systems"
