kind = "DojoContract"
class_hash = "0x969680ca5223f549514e1d8f817366ad9fd1b2954de9488d1fa3ab848f877e"
original_class_hash = "0x969680ca5223f549514e1d8f817366ad9fd1b2954de9488d1fa3ab848f877e"
base_class_hash = "0x0"
abi = "manifests/prod/abis/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::trade::contracts::trade_systems::trade_systems"
