kind = "DojoContract"
class_hash = "0x517f10da95354a3dd075bbc657137bd5e8a3215c1a954168d33ca47a7f64700"
original_class_hash = "0x517f10da95354a3dd075bbc657137bd5e8a3215c1a954168d33ca47a7f64700"
base_class_hash = "0x0"
abi = "manifests/prod/abis/base/contracts/eternum_systems_config_contracts_config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
