kind = "DojoModel"
class_hash = "0x6005ab5721faf4bfa759290e630f0bc003855641d44dde2b2855dc88babdebf"
original_class_hash = "0x6005ab5721faf4bfa759290e630f0bc003855641d44dde2b2855dc88babdebf"
abi = "manifests/release/abis/base/models/eternum_models_config_attack_config.json"
name = "eternum::models::config::attack_config"

[[members]]
name = "entity_type"
type = "u128"
key = true

[[members]]
name = "max_value"
type = "u128"
key = false
