kind = "DojoModel"
class_hash = "0xdc0e3fddfc4863304a3c4f5e4ef1c1d0ca5f50409c7b02f61a2128deb3d715"
original_class_hash = "0xdc0e3fddfc4863304a3c4f5e4ef1c1d0ca5f50409c7b02f61a2128deb3d715"
abi = "manifests/release/abis/base/models/eternum_models_order_orders.json"
name = "eternum::models::order::orders"

[[members]]
name = "order_id"
type = "u128"
key = true

[[members]]
name = "hyperstructure_count"
type = "u128"
key = false
