kind = "DojoModel"
class_hash = "0x4549eb4e0df599e8ac1f8d76f7b84b28e25ed66f9a1b72dd7e05f590712b71f"
original_class_hash = "0x4549eb4e0df599e8ac1f8d76f7b84b28e25ed66f9a1b72dd7e05f590712b71f"
abi = "manifests/release/abis/base/models/eternum_models_inventory_inventory.json"
name = "eternum::models::inventory::inventory"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "items_key"
type = "felt252"
key = false

[[members]]
name = "items_count"
type = "u128"
key = false
