kind = "DojoModel"
class_hash = "0xd53f20a2dad42d3a4c3fb32788a37840392ae549312a2ce0169b7931e82bb9"
original_class_hash = "0xd53f20a2dad42d3a4c3fb32788a37840392ae549312a2ce0169b7931e82bb9"
abi = "manifests/release/abis/base/models/eternum_models_config_leveling_config.json"
name = "eternum::models::config::leveling_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "decay_interval"
type = "u64"
key = false

[[members]]
name = "max_level"
type = "u64"
key = false

[[members]]
name = "decay_scaled"
type = "u128"
key = false

[[members]]
name = "cost_percentage_scaled"
type = "u128"
key = false

[[members]]
name = "base_multiplier"
type = "u128"
key = false

[[members]]
name = "wheat_base_amount"
type = "u128"
key = false

[[members]]
name = "fish_base_amount"
type = "u128"
key = false

[[members]]
name = "resource_1_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_1_cost_count"
type = "u32"
key = false

[[members]]
name = "resource_2_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_2_cost_count"
type = "u32"
key = false

[[members]]
name = "resource_3_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_3_cost_count"
type = "u32"
key = false
