kind = "DojoModel"
class_hash = "0x7116d7211e346762ca345915633b9decea32c3d2f49b18daf3a0c38805e950c"
original_class_hash = "0x7116d7211e346762ca345915633b9decea32c3d2f49b18daf3a0c38805e950c"
abi = "manifests/release/abis/base/models/eternum_models_hyperstructure_settlement.json"
name = "eternum::models::hyperstructure::settlement"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "realm_id"
type = "u128"
key = false

[[members]]
name = "resource_types_packed"
type = "u128"
key = false

[[members]]
name = "resource_types_count"
type = "u8"
key = false

[[members]]
name = "order"
type = "u8"
key = false

[[members]]
name = "tax_paid"
type = "bool"
key = false

[[members]]
name = "last_time_tax_paid"
type = "u32"
key = false
