kind = "DojoModel"
class_hash = "0xa5ef587fca6a906186339fcbb0510a04778a007053bf778cc16512b1b2f2a6"
original_class_hash = "0xa5ef587fca6a906186339fcbb0510a04778a007053bf778cc16512b1b2f2a6"
abi = "manifests/release/abis/base/models/eternum_models_resources_owned_resources_tracker.json"
name = "eternum::models::resources::owned_resources_tracker"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "resource_types"
type = "u32"
key = false
