kind = "DojoModel"
class_hash = "0x41e36fe1bb5bc9aa0c2e6ccb1e6aead3b0801e5d043d016f60edfa7d5bcbf7c"
name = "eternum::models::name::address_name"

[[members]]
name = "address"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
