kind = "DojoModel"
class_hash = "0x68ba8243431195bf65c2b7631beb61a656e7cc07e4adf0dae5deeb15d34ed60"
name = "eternum::models::movable::arrival_time"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "arrives_at"
type = "u64"
key = false
