kind = "DojoModel"
class_hash = "0x6dbdb27adaf95920ee6e3c9e3698e693eb9dd622dffb2fa43181f3696234598"
name = "eternum::models::bank::bank"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "exists"
type = "bool"
key = false
