kind = "DojoModel"
class_hash = "0x1278bd7f4b0762ecc27fdb16f591aad71e94df0b399a7eb41454571cffa2c0"
name = "eternum::models::bank::bank_swap_resource_cost"

[[members]]
name = "bank_gives_resource_type"
type = "u8"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "resource_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_cost_count"
type = "u32"
key = false
