kind = "DojoModel"
class_hash = "0x7aa3669703f93e3c048017c4582c152948742be68d1ffc025be7107dfa5e1c8"
name = "eternum::models::config::bank_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "lords_cost"
type = "u128"
key = false

[[members]]
name = "lp_fee_scaled"
type = "u128"
key = false
