kind = "DojoModel"
class_hash = "0x4279f10b49a2ac6bc2eff60991517cd7ee06b7fa461f185be1da77a46d98f68"
name = "eternum::models::bank::bank::bank"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "swap_fee"
type = "u128"
key = false
