kind = "DojoModel"
class_hash = "0x7b94d668dc7397b6c6e7702f1c4e593eb73580fa66a0e3d58e5c22589cca5ea"
name = "eternum::models::bank::bank::bank"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "owner_fee_scaled"
type = "u128"
key = false
