kind = "DojoModel"
class_hash = "0x3d06e06c1bbbfd950da25cb6cb9447b83eceecfdfbabaa49a04b649f3bc4a4"
abi = "abis/base/models/bank.json"
name = "eternum::models::bank::bank"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "exists"
type = "bool"
key = false
