kind = "DojoModel"
class_hash = "0x4f2eb92a08aeec4e640909db2e812ade1d1096db1c12a0c2f1a18340a581cb3"
abi = "abis/base/models/capacity.json"
name = "eternum::models::capacity::capacity"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "weight_gram"
type = "u128"
key = false
