kind = "DojoModel"
class_hash = "0x5153f1a9efa8d4d037ad64ff536d9ac4c0669c053acd8b5945ad36bd31423f0"
name = "eternum::models::capacity::capacity"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "weight_gram"
type = "u128"
key = false
