kind = "DojoModel"
class_hash = "0x44524012d1ee3570c3df0701973a88b7cd4f2c757e9cf59af53b132137a4e5f"
name = "eternum::models::config::capacity_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "carry_capacity_config_id"
type = "u128"
key = true

[[members]]
name = "entity_type"
type = "u128"
key = false

[[members]]
name = "weight_gram"
type = "u128"
key = false
