kind = "DojoModel"
class_hash = "0x19b4ffea3cd1e74320cbf417592bc1ca5af16d9f0fc83d2dfc072372573bbc6"
name = "eternum::models::caravan::caravan_members"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "key"
type = "u128"
key = false

[[members]]
name = "count"
type = "u32"
key = false
