kind = "DojoModel"
class_hash = "0x786a217d897efd6eaf0cc6737ba53552a1e94738a49e2edaf7192aa7a6be942"
name = "eternum::models::config::combat_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "stealing_trial_count"
type = "u32"
key = false

[[members]]
name = "wheat_burn_per_soldier"
type = "u128"
key = false

[[members]]
name = "fish_burn_per_soldier"
type = "u128"
key = false
