kind = "DojoModel"
class_hash = "0x4e3c69259a75935e43ad3ca32758d60707eb4793f1472ffb68504a86f960d7f"
name = "eternum::models::resources::detached_resource"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = false

[[members]]
name = "resource_amount"
type = "u128"
key = false
