kind = "DojoModel"
class_hash = "0x5407e40ae02a1a2b528f43b36f276088ef49e4b7a11a78513ac01041818bce8"
name = "eternum::models::owner::entity_owner"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "entity_owner_id"
type = "u128"
key = false
