kind = "DojoModel"
class_hash = "0x2313353b682b835ca49ffa3d744c14829ddedd364649ebe12e7ff885bae3543"
name = "eternum::models::config::health_config"

[[members]]
name = "entity_type"
type = "u128"
key = true

[[members]]
name = "resource_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_cost_count"
type = "u32"
key = false

[[members]]
name = "max_value"
type = "u128"
key = false
