kind = "DojoModel"
class_hash = "0x68265cc17f987098c48675632755bfce0ab8b79bb00923562ea13c320411311"
name = "eternum::models::hyperstructure::hyper_structure_v_2"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "owner"
type = "u128"
key = false

[[members]]
name = "completed"
type = "bool"
key = false

[[members]]
name = "settlement_cost"
type = "u32"
key = false

[[members]]
name = "settlment_tax"
type = "u32"
key = false
