kind = "DojoModel"
class_hash = "0x39b25dc2f30bfd8ed6d49231cd91a0dc9cda511f843aa1716cbaa519b96acd9"
name = "eternum::models::hyperstructure::hyper_structure"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "hyperstructure_type"
type = "u8"
key = false

[[members]]
name = "controlling_order"
type = "u8"
key = false

[[members]]
name = "completed"
type = "bool"
key = false

[[members]]
name = "completion_cost_id"
type = "u128"
key = false

[[members]]
name = "completion_resource_count"
type = "u32"
key = false
