kind = "DojoModel"
class_hash = "0x13b197fc3230e589b68eb5e582b0ed1f9b790b744c15e95ef9741951c20767e"
name = "eternum::models::config::labor_buildings_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "level_multiplier"
type = "u128"
key = false

[[members]]
name = "level_discount_mag"
type = "u128"
key = false

[[members]]
name = "resources_category_1"
type = "u128"
key = false

[[members]]
name = "resources_category_1_count"
type = "u8"
key = false

[[members]]
name = "resources_category_2"
type = "u128"
key = false

[[members]]
name = "resources_category_2_count"
type = "u8"
key = false

[[members]]
name = "resources_category_3"
type = "u128"
key = false

[[members]]
name = "resources_category_3_count"
type = "u8"
key = false

[[members]]
name = "resources_category_4"
type = "u128"
key = false

[[members]]
name = "resources_category_4_count"
type = "u8"
key = false
