kind = "DojoModel"
class_hash = "0x6844de55347bcd24f16c8dfbf4b9a63dd5a6b40fd707242b8902599cb23392f"
name = "eternum::models::buildings::labor_building"

[[members]]
name = "realm_entity_id"
type = "u128"
key = true

[[members]]
name = "building_type"
type = "u8"
key = false

[[members]]
name = "labor_count"
type = "u128"
key = false

[[members]]
name = "level"
type = "u128"
key = false
