kind = "DojoModel"
class_hash = "0x860f3920f0001866cd70f82bb9e6717ff89db8929074b407f6f8177c87bffb"
name = "eternum::models::config::labor_cost_resources"

[[members]]
name = "resource_type_labor"
type = "felt252"
key = true

[[members]]
name = "resource_types_packed"
type = "u128"
key = false

[[members]]
name = "resource_types_count"
type = "u8"
key = false
