kind = "DojoModel"
class_hash = "0x76601e82bc597e5485558932d765102aa4ee8d67aebca1dc8a5d65eace131c1"
name = "eternum::models::level::level"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "level"
type = "u64"
key = false

[[members]]
name = "valid_until"
type = "u64"
key = false
