kind = "DojoModel"
class_hash = "0x239780f3145ed140e45e72cc45c3d04fec26e560c4874181e5604e427ca030a"
name = "eternum::models::config::map_explore_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "reward_resource_amount"
type = "u128"
key = false
