kind = "DojoModel"
class_hash = "0x7f0ac539b056435fe85412531970da7df4857809fcea21d844bf57c1dd4b5e6"
name = "eternum::models::bank::market::market"

[[members]]
name = "bank_entity_id"
type = "u128"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "lords_amount"
type = "u128"
key = false

[[members]]
name = "resource_amount"
type = "u128"
key = false

[[members]]
name = "fee_resource_amount"
type = "u128"
key = false

[[members]]
name = "fee_lords_amount"
type = "u128"
key = false
