kind = "DojoModel"
class_hash = "0x5ceb97f06877d30524f6396add4afc50bf419b749e6832d764c6da66c515c40"
abi = "abis/base/models/movable.json"
name = "eternum::models::movable::movable"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "sec_per_km"
type = "u16"
key = false

[[members]]
name = "blocked"
type = "bool"
key = false

[[members]]
name = "round_trip"
type = "bool"
key = false

[[members]]
name = "start_coord_x"
type = "u128"
key = false

[[members]]
name = "start_coord_y"
type = "u128"
key = false

[[members]]
name = "intermediate_coord_x"
type = "u128"
key = false

[[members]]
name = "intermediate_coord_y"
type = "u128"
key = false
