kind = "DojoModel"
class_hash = "0x758bd21197a7b51f79b126eef5639b668cd5f026829bbad4439e3ad205bba93"
name = "eternum::models::position::position"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "x"
type = "u128"
key = false

[[members]]
name = "y"
type = "u128"
key = false
