kind = "DojoModel"
class_hash = "0x4b8018ce1fed1fb100173e0308c8d900c4d5cd4189a10a9f9188e321c722cca"
name = "eternum::models::production::production_material_config"

[[members]]
name = "material_resource_type"
type = "u8"
key = true

[[members]]
name = "produced_resource_type_1"
type = "u8"
key = false

[[members]]
name = "produced_resource_type_2"
type = "u8"
key = false
