kind = "DojoModel"
class_hash = "0xb1a8bc0402c80382937d1339c419e1507af121146df42a3d45c136c18f60be"
name = "eternum::models::production::production_config"

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u128"
key = false

[[members]]
name = "cost_resource_type_1"
type = "u8"
key = false

[[members]]
name = "cost_resource_type_1_amount"
type = "u128"
key = false

[[members]]
name = "cost_resource_type_2"
type = "u8"
key = false

[[members]]
name = "cost_resource_type_2_amount"
type = "u128"
key = false
