kind = "DojoModel"
class_hash = "0x4a36334ec33f3c0973e78b56540c36f6d706a3ac8a310675f56e0d95584b144"
name = "eternum::models::quantity::quantity_tracker"

[[members]]
name = "entity_id"
type = "felt252"
key = true

[[members]]
name = "count"
type = "u128"
key = false
