kind = "DojoModel"
class_hash = "0x3bfa1f99d09a74682e0f626d58d2b74e79ce652cf0ade038a179b581772f8fe"
name = "eternum::models::quantity::quantity"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u128"
key = false
