kind = "DojoModel"
class_hash = "0x58fddb9c02a4d4303b1145a52618d501a45dd50686b4bc512881fda6c10553c"
abi = "abis/base/models/quantity.json"
name = "eternum::models::quantity::quantity"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u128"
key = false
