kind = "DojoModel"
class_hash = "0x7095b1999af3887e0f646b84bbf8f4fbc0d1716b5ef1f875a55ab35a5b837a6"
abi = "abis/base/models/resource_chest.json"
name = "eternum::models::resources::resource_chest"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "locked_until"
type = "u64"
key = false

[[members]]
name = "resources_count"
type = "u32"
key = false
