kind = "DojoModel"
class_hash = "0x37722e202b1bef890703a03ef462e8bfb8590305911ef5c1c1a5987742f44"
name = "eternum::models::resources::resource_cost"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = false

[[members]]
name = "amount"
type = "u128"
key = false
