kind = "DojoModel"
class_hash = "0x2513b34490c19cb97e031120b184f5809e451814da58774f45e495c4b943d5e"
name = "eternum::models::resources::resource_chest"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "locked_until"
type = "u64"
key = false

[[members]]
name = "resources_count"
type = "u32"
key = false
