kind = "DojoModel"
class_hash = "0x32e870ab59af49fa3de3ffde28cef9661e3ebee7728e698b725560afd62a425"
name = "eternum::models::config::road_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "resource_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_cost_count"
type = "u32"
key = false

[[members]]
name = "speed_up_by"
type = "u64"
key = false
