kind = "DojoModel"
class_hash = "0x4f05ea809f737a377d363cec4e16ba2b93a00347143852587c9be200fa467ab"
name = "eternum::models::road::road"

[[members]]
name = "start_coord_x"
type = "u128"
key = true

[[members]]
name = "start_coord_y"
type = "u128"
key = true

[[members]]
name = "end_coord_x"
type = "u128"
key = true

[[members]]
name = "end_coord_y"
type = "u128"
key = true

[[members]]
name = "usage_count"
type = "u32"
key = false
