kind = "DojoModel"
class_hash = "0xabf8700dc8b902b41a66b939e0979633e3468543abcb08705d18af6166ca90"
abi = "abis/base/models/speed_config.json"
name = "eternum::models::config::speed_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "speed_config_id"
type = "u128"
key = true

[[members]]
name = "entity_type"
type = "u128"
key = false

[[members]]
name = "sec_per_km"
type = "u16"
key = false
