kind = "DojoModel"
class_hash = "0x750179a6e753a69d4be20c9365866bc647ceac150e1eb4f3b4542d3f7d305a5"
name = "eternum::models::map::tile"

[[members]]
name = "_col"
type = "u128"
key = true

[[members]]
name = "_row"
type = "u128"
key = true

[[members]]
name = "col"
type = "u128"
key = false

[[members]]
name = "row"
type = "u128"
key = false

[[members]]
name = "explored_by_id"
type = "u128"
key = false

[[members]]
name = "explored_at"
type = "u64"
key = false

[[members]]
name = "biome"
type = "Biome"
key = false
