kind = "DojoModel"
class_hash = "0x615d6d2662e2c0b81a57a13c68cdf419bb1e1077595685d755f6275998b73ab"
name = "eternum::models::trade::trade"

[[members]]
name = "trade_id"
type = "u128"
key = true

[[members]]
name = "maker_id"
type = "u128"
key = false

[[members]]
name = "maker_resource_chest_id"
type = "u128"
key = false

[[members]]
name = "maker_transport_id"
type = "u128"
key = false

[[members]]
name = "taker_id"
type = "u128"
key = false

[[members]]
name = "taker_resource_chest_id"
type = "u128"
key = false

[[members]]
name = "taker_transport_id"
type = "u128"
key = false

[[members]]
name = "expires_at"
type = "u64"
key = false
