kind = "DojoModel"
class_hash = "0x30b6a73c8dab8509eb0909507940d854e9a9e31f04a517b2c64f1a4d91e8fe7"
abi = "abis/base/models/trade.json"
name = "eternum::models::trade::trade"

[[members]]
name = "trade_id"
type = "u128"
key = true

[[members]]
name = "maker_id"
type = "u128"
key = false

[[members]]
name = "maker_resource_chest_id"
type = "u128"
key = false

[[members]]
name = "maker_transport_id"
type = "u128"
key = false

[[members]]
name = "taker_id"
type = "u128"
key = false

[[members]]
name = "taker_resource_chest_id"
type = "u128"
key = false

[[members]]
name = "taker_transport_id"
type = "u128"
key = false

[[members]]
name = "expires_at"
type = "u64"
key = false
