kind = "DojoModel"
class_hash = "0x1fed2439b5d152a55f1785e39f0bb329b5368e6661ec73de806635417243418"
name = "eternum::models::config::travel_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "free_transport_per_city"
type = "u128"
key = false
