kind = "DojoModel"
class_hash = "0x548196da2dd2b154603e85c738188a1b4822a6d2de6dcd24cf8b964975f65e4"
abi = "abis/base/models/world_config.json"
name = "eternum::models::config::world_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "admin_address"
type = "ContractAddress"
key = false

[[members]]
name = "realm_l2_contract"
type = "ContractAddress"
key = false
