kind = "DojoContract"
class_hash = "0x2b00ccd8064896a8cfa6c5c9caed3ed6ed29b64e862282bf62971a674991323"
abi = "abis/base/contracts/bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems"
