kind = "DojoContract"
class_hash = "0x7a91f54fafc0554bd197313a126e4e5c566e9f333dea4ac96b0f48811e57465"
abi = "abis/base/contracts/bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems"
