kind = "DojoContract"
class_hash = "0x41afe805f043246a2fa860df12ed0d19cf8b2e59305df5d7ee5ee91c308d7c0"
abi = "abis/base/contracts/bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems::bank_systems"
