kind = "DojoContract"
class_hash = "0x574e0575f86a0adf4016d246fd3156a6cced25537f1e8bc1c6ed72682bd2d62"
abi = "abis/base/contracts/bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems::bank_systems"
