kind = "DojoContract"
class_hash = "0x23597361dd84a1f393d4c98eb4b7a3f9397c06a7207ccee65c05351ea5564f9"
abi = "abis/base/contracts/bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems::bank_systems"
