kind = "DojoContract"
class_hash = "0x1bf3185cf3c04c927ad2fd47126527d0b29b1b5d2c592d9690879f202f00052"
abi = "abis/base/contracts/combat_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::combat::contracts::combat_systems"
