kind = "DojoContract"
class_hash = "0x26bfb1744e3c678874aae98a8563e2d014f11c8ee5721ed8fa4c308b391b269"
abi = "abis/base/contracts/config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
