kind = "DojoContract"
class_hash = "0x50b52df39f0b9495625ac869e13ccf7801728a6c6b4587d52a54d02dddbf09f"
abi = "abis/base/contracts/config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
