kind = "DojoContract"
class_hash = "0x457276debceacbc9f006754f67d3b4e558b0495b6d0368a2ebe55dbf53c907b"
abi = "abis/base/contracts/config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
