kind = "DojoContract"
class_hash = "0x2d7e9b4cc4843bc6510a7142c3a12eba1c398c1e6662a3694731e3bdd0c27c4"
abi = "abis/base/contracts/config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
