kind = "DojoContract"
class_hash = "0x1ed6e020c514a78dea817f6f16af63ddbc20ad30f3f878fb2a15404d801fd8b"
abi = "abis/base/contracts/leveling_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::leveling::contracts::leveling_systems"
