kind = "DojoContract"
class_hash = "0x5fbd24507f8495e77693ff885a6f1a8f1a2b0479d73c900bae1490ee97de080"
abi = "abis/base/contracts/liquidity_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::liquidity_systems::liquidity_systems"
