kind = "DojoContract"
class_hash = "0x17170fb5aad39807b36991c78ed5663ffc7e48d299241e01e9f5cb83d5ee088"
abi = "abis/base/contracts/liquidity_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::liquidity_systems::liquidity_systems"
