kind = "DojoContract"
class_hash = "0x13bb23c691c120a7e42924ef13af12d855ddd80e4f6c5c464b51ae3348e6b6f"
abi = "abis/base/contracts/map_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::map::contracts::map_systems"
