kind = "DojoContract"
class_hash = "0x2b58a8de68df822d696fce344ef1efeb0ab6f1d9ef6fa4f49a15f9d75bb5c8b"
abi = "abis/base/contracts/map_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::map::contracts::map_systems"
