kind = "DojoContract"
class_hash = "0x524c743435e6daebf5ba878ac986e1807db730ea2f446a64aa0f72f334e0e4c"
abi = "abis/base/contracts/realm_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::realm::contracts::realm_systems"
