kind = "DojoContract"
class_hash = "0x1c7741f14f29d03ef1ee0771359fa7b0cdd8f9254a60521b4a35076775bef4"
abi = "abis/base/contracts/swap_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::swap_systems::swap_systems"
