kind = "DojoContract"
class_hash = "0x455ea22eeb297373d9e987823df6fe0591735e862a2d4454af2273ed5f5d3a6"
abi = "abis/base/contracts/swap_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::swap_systems::swap_systems"
