kind = "DojoContract"
class_hash = "0x73cc9238488d651eb395329ef31247188c8c63ec2430d9563d83e728b94beb2"
abi = "abis/base/contracts/trade_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::trade::contracts::trade_systems::trade_systems"
