kind = "DojoModel"
class_hash = "0x64fce5d205ac11fc7f86ecec478c5f2310f889948da8230ad1c57cda5e64a5b"
original_class_hash = "0x64fce5d205ac11fc7f86ecec478c5f2310f889948da8230ad1c57cda5e64a5b"
abi = "manifests/dev/abis/base/models/eternum_models_labor_labor.json"
name = "eternum::models::labor::labor"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "balance"
type = "u64"
key = false

[[members]]
name = "last_harvest"
type = "u64"
key = false

[[members]]
name = "multiplier"
type = "u64"
key = false
