kind = "DojoModel"
class_hash = "0x6e6461b60f55b5057c543a749b4205619c5ffb37b784ef58b3631e6e4300ce5"
original_class_hash = "0x6e6461b60f55b5057c543a749b4205619c5ffb37b784ef58b3631e6e4300ce5"
abi = "manifests/dev/abis/base/models/eternum_models_position_position.json"
name = "eternum::models::position::position"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "x"
type = "u128"
key = false

[[members]]
name = "y"
type = "u128"
key = false
