kind = "DojoModel"
class_hash = "0x17f82236abdf86e3a144f0c624e852a227dff3f008451c1fd58e961bb8ea1"
original_class_hash = "0x17f82236abdf86e3a144f0c624e852a227dff3f008451c1fd58e961bb8ea1"
abi = "manifests/dev/abis/base/models/eternum_models_movable_arrival_time.json"
name = "eternum::models::movable::arrival_time"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "arrives_at"
type = "u64"
key = false
