kind = "DojoModel"
class_hash = "0x504034bca2e531a745ca797be51c9dfc8c1d0b27678337e37472d0c35370c81"
original_class_hash = "0x504034bca2e531a745ca797be51c9dfc8c1d0b27678337e37472d0c35370c81"
abi = "manifests/dev/abis/base/models/eternum_models_production_production.json"
name = "eternum::models::production::production"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "building_count"
type = "u128"
key = false

[[members]]
name = "production_rate"
type = "u128"
key = false

[[members]]
name = "consumption_rate"
type = "u128"
key = false

[[members]]
name = "last_updated_tick"
type = "u64"
key = false

[[members]]
name = "input_finish_tick"
type = "u64"
key = false
