kind = "DojoModel"
class_hash = "0x42005840d8a8d91de1468cf89f37095676b5d7892349f1df5b0430277e55ac4"
original_class_hash = "0x42005840d8a8d91de1468cf89f37095676b5d7892349f1df5b0430277e55ac4"
abi = "manifests/dev/abis/base/models/eternum_models_combat_health.json"
name = "eternum::models::combat::health"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u128"
key = false
