kind = "DojoModel"
class_hash = "0x45dc71c64264ed6d98a00e64cf82d3fa83d6a333444578d9bf9d37af4255cbb"
original_class_hash = "0x45dc71c64264ed6d98a00e64cf82d3fa83d6a333444578d9bf9d37af4255cbb"
abi = "manifests/dev/abis/base/models/eternum_models_owner_entity_owner.json"
name = "eternum::models::owner::entity_owner"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "entity_owner_id"
type = "u128"
key = false
