kind = "DojoModel"
class_hash = "0xc6dd5dceb0c1f3129ee088954553d2fcefc73bcf77c8b4976ec2f6f3215a38"
original_class_hash = "0xc6dd5dceb0c1f3129ee088954553d2fcefc73bcf77c8b4976ec2f6f3215a38"
abi = "manifests/dev/abis/base/models/eternum_models_config_defence_config.json"
name = "eternum::models::config::defence_config"

[[members]]
name = "entity_type"
type = "u128"
key = true

[[members]]
name = "max_value"
type = "u128"
key = false
