kind = "DojoModel"
class_hash = "0x40f490e41656659252e49e90b78f5370d40860a49431e8a6a6d7e210f7f99d2"
original_class_hash = "0x40f490e41656659252e49e90b78f5370d40860a49431e8a6a6d7e210f7f99d2"
abi = "manifests/dev/abis/base/models/eternum_models_bank_market_market.json"
name = "eternum::models::bank::market::market"

[[members]]
name = "bank_entity_id"
type = "u128"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "lords_amount"
type = "u128"
key = false

[[members]]
name = "resource_amount"
type = "u128"
key = false
