kind = "DojoModel"
class_hash = "0x7a41f2d0bc2abf22747114d4c8f089a00a9e8636b7bd5a40f02f0728b90eadd"
original_class_hash = "0x7a41f2d0bc2abf22747114d4c8f089a00a9e8636b7bd5a40f02f0728b90eadd"
abi = "manifests/dev/abis/base/models/eternum_models_config_labor_cost_resources.json"
name = "eternum::models::config::labor_cost_resources"

[[members]]
name = "resource_type_labor"
type = "felt252"
key = true

[[members]]
name = "resource_types_packed"
type = "u128"
key = false

[[members]]
name = "resource_types_count"
type = "u8"
key = false
