kind = "DojoModel"
class_hash = "0x4c2e190b23c7bfa335c119ee082f5b5d137fc6406baf8a5df636e20bda7aeef"
original_class_hash = "0x4c2e190b23c7bfa335c119ee082f5b5d137fc6406baf8a5df636e20bda7aeef"
abi = "manifests/dev/abis/base/models/eternum_models_buildings_labor_building.json"
name = "eternum::models::buildings::labor_building"

[[members]]
name = "realm_entity_id"
type = "u128"
key = true

[[members]]
name = "building_type"
type = "u8"
key = false

[[members]]
name = "labor_count"
type = "u128"
key = false

[[members]]
name = "level"
type = "u128"
key = false
