kind = "DojoModel"
class_hash = "0x6c7b0024e1673bf80f5b430bdab476b9168d7e47be52f7d423e168916fcaf9f"
original_class_hash = "0x6c7b0024e1673bf80f5b430bdab476b9168d7e47be52f7d423e168916fcaf9f"
abi = "manifests/dev/abis/base/models/eternum_models_config_production_material_config.json"
name = "eternum::models::config::production_material_config"

[[members]]
name = "material_resource_type"
type = "u8"
key = true

[[members]]
name = "produced_resource_type_1"
type = "u8"
key = false

[[members]]
name = "produced_resource_type_2"
type = "u8"
key = false
