kind = "DojoModel"
class_hash = "0x2d24eb8c28fb4669501069fa338440e0619e4cb2148d7cc68fe5c93fa633572"
original_class_hash = "0x2d24eb8c28fb4669501069fa338440e0619e4cb2148d7cc68fe5c93fa633572"
abi = "manifests/dev/abis/base/models/eternum_models_config_combat_config.json"
name = "eternum::models::config::combat_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "stealing_trial_count"
type = "u32"
key = false

[[members]]
name = "wheat_burn_per_soldier"
type = "u128"
key = false

[[members]]
name = "fish_burn_per_soldier"
type = "u128"
key = false
