kind = "DojoModel"
class_hash = "0x7aa13fcbe2df0259b18040fb9c74d0c47d51de494fef7004081ac230212b4c9"
original_class_hash = "0x7aa13fcbe2df0259b18040fb9c74d0c47d51de494fef7004081ac230212b4c9"
abi = "manifests/dev/abis/base/models/eternum_models_bank_bank_swap_resource_cost.json"
name = "eternum::models::bank::bank_swap_resource_cost"

[[members]]
name = "bank_gives_resource_type"
type = "u8"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "resource_cost_id"
type = "u128"
key = false

[[members]]
name = "resource_cost_count"
type = "u32"
key = false
