[package]
cairo-version = "2.4.0"
name = "eternum"
version = "0.3.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "98aadc7e3f12dbb026e853604fe2cc061451cc8a" }
cubit = { git = "https://github.com/akhercha/cubit", rev = "d3869a3f0c47e5ed229bbbfe2fce3fc0510cbc8a" }
# TODO: use dojo_defi when works with latest nightly
#dojo_defi = { git = "https://github.com/dojoengine/dojo" }

[tool.dojo.env]
world_address = "0x5cb4ce060de62a7b6bfd4cb70fd4ae3196bfe399c372cb0863e632ba8cc73ef"

## dev
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

## prod
#account_address = "0x178af2a04c0c16ad688ebac1c826b4be27b440979296b50947400691dcc4e7a"
#private_key = "0x22b6155e4cf0748ac40306efa1a42520705c956d0ce6331d72bc1579f7f9918"

[[target.dojo]]

[lib]

[tool.dojo.world]
name = "Realms: Eternum"
description = "Rule the Realms"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"
