kind = "DojoModel"
class_hash = "0x77df534a3fd262bcfd2b6f7b0ba84cc5082f966fc6c00b7eee9d466a452af9d"
original_class_hash = "0x77df534a3fd262bcfd2b6f7b0ba84cc5082f966fc6c00b7eee9d466a452af9d"
abi = "manifests/prod/abis/base/models/eternum_models_bank_liquidity_liquidity.json"
name = "eternum::models::bank::liquidity::liquidity"

[[members]]
name = "bank_entity_id"
type = "u128"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "shares"
type = "Fixed"
key = false
