kind = "DojoModel"
class_hash = "0x6a94f276c7680df58ea651b5689d748eefe4d99dba6821ebb3864c18b0ec7f2"
original_class_hash = "0x6a94f276c7680df58ea651b5689d748eefe4d99dba6821ebb3864c18b0ec7f2"
abi = "manifests/prod/abis/base/models/eternum_models_road_road.json"
name = "eternum::models::road::road"

[[members]]
name = "start_coord_x"
type = "u128"
key = true

[[members]]
name = "start_coord_y"
type = "u128"
key = true

[[members]]
name = "end_coord_x"
type = "u128"
key = true

[[members]]
name = "end_coord_y"
type = "u128"
key = true

[[members]]
name = "usage_count"
type = "u32"
key = false
