kind = "DojoModel"
class_hash = "0x2b6687b50d54cf576758c9aef79d4583687558c6ba19fa52c8c68959a017f30"
original_class_hash = "0x2b6687b50d54cf576758c9aef79d4583687558c6ba19fa52c8c68959a017f30"
abi = "manifests/prod/abis/base/models/eternum_models_buildings_building.json"
name = "eternum::models::buildings::building"

[[members]]
name = "outer_col"
type = "u128"
key = true

[[members]]
name = "outer_row"
type = "u128"
key = true

[[members]]
name = "inner_col"
type = "u128"
key = true

[[members]]
name = "inner_row"
type = "u128"
key = true

[[members]]
name = "category"
type = "BuildingCategory"
key = false

[[members]]
name = "produced_resource_type"
type = "u8"
key = false

[[members]]
name = "bonus_percent"
type = "u128"
key = false

[[members]]
name = "entity_id"
type = "u128"
key = false

[[members]]
name = "outer_entity_id"
type = "u128"
key = false
