kind = "DojoModel"
class_hash = "0x4e30e10d1da1df4f519df3c2b59cf0beb856c014f3fa9f8e91ecfb97c386e94"
original_class_hash = "0x4e30e10d1da1df4f519df3c2b59cf0beb856c014f3fa9f8e91ecfb97c386e94"
abi = "manifests/prod/abis/base/models/eternum_models_bank_bank_bank_accounts.json"
name = "eternum::models::bank::bank::bank_accounts"

[[members]]
name = "bank_entity_id"
type = "u128"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "entity_id"
type = "u128"
key = false
