kind = "DojoModel"
class_hash = "0x52122e15cf951b767242bcc20133d8e588c056843ff12bee8192a2d3709f2f2"
original_class_hash = "0x52122e15cf951b767242bcc20133d8e588c056843ff12bee8192a2d3709f2f2"
abi = "manifests/prod/abis/base/models/eternum_models_config_production_config.json"
name = "eternum::models::config::production_config"

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u128"
key = false

[[members]]
name = "input_count"
type = "u128"
key = false

[[members]]
name = "output_count"
type = "u128"
key = false
