kind = "DojoModel"
class_hash = "0x415bb26d1ecab39598eb891a0b67a230cce78f68b6ae649177e8f06a53a28ff"
original_class_hash = "0x415bb26d1ecab39598eb891a0b67a230cce78f68b6ae649177e8f06a53a28ff"
abi = "manifests/prod/abis/base/models/eternum_models_config_tick_config.json"
name = "eternum::models::config::tick_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "max_moves_per_tick"
type = "u8"
key = false

[[members]]
name = "tick_interval_in_seconds"
type = "u64"
key = false
