kind = "DojoModel"
class_hash = "0x6066587bf977a27f0c81b77bf964deb20663a254ee96e57b13412380be3abb2"
original_class_hash = "0x6066587bf977a27f0c81b77bf964deb20663a254ee96e57b13412380be3abb2"
abi = "manifests/prod/abis/base/models/eternum_models_owner_owner.json"
name = "eternum::models::owner::owner"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
