kind = "DojoModel"
class_hash = "0x2f836136a4001ce8df8bdd5a31d773b237cb34eda2fc39dbd2f651d23f6a042"
original_class_hash = "0x2f836136a4001ce8df8bdd5a31d773b237cb34eda2fc39dbd2f651d23f6a042"
abi = "manifests/prod/abis/base/models/eternum_models_config_capacity_config.json"
name = "eternum::models::config::capacity_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "carry_capacity_config_id"
type = "u128"
key = true

[[members]]
name = "entity_type"
type = "u128"
key = false

[[members]]
name = "weight_gram"
type = "u128"
key = false
