kind = "DojoModel"
class_hash = "0x6e9530bb295ee165c8fc8678f6b85bb5900516a71b89f46e65ed8cf1a738ada"
original_class_hash = "0x6e9530bb295ee165c8fc8678f6b85bb5900516a71b89f46e65ed8cf1a738ada"
abi = "manifests/prod/abis/base/models/eternum_models_metadata_entity_metadata.json"
name = "eternum::models::metadata::entity_metadata"

[[members]]
name = "entity_id"
type = "u128"
key = true

[[members]]
name = "entity_type"
type = "u128"
key = false
