kind = "DojoModel"
class_hash = "0x2df5a3be56c9e3ad9707acbad12498931db4b260355a89fb04e2b9337ebc746"
original_class_hash = "0x2df5a3be56c9e3ad9707acbad12498931db4b260355a89fb04e2b9337ebc746"
abi = "manifests/prod/abis/base/models/eternum_models_resources_resource_allowance.json"
name = "eternum::models::resources::resource_allowance"

[[members]]
name = "owner_entity_id"
type = "u128"
key = true

[[members]]
name = "approved_entity_id"
type = "u128"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
