kind = "DojoModel"
class_hash = "0x53d198ca12ff8c9cdea31a695305401ef41eee8001ca2a279b1c52b5de97999"
original_class_hash = "0x53d198ca12ff8c9cdea31a695305401ef41eee8001ca2a279b1c52b5de97999"
abi = "manifests/prod/abis/base/models/eternum_models_production_production_input.json"
name = "eternum::models::production::production_input"

[[members]]
name = "output_resource_type"
type = "u8"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "input_resource_type"
type = "u8"
key = false

[[members]]
name = "input_resource_amount"
type = "u128"
key = false
