kind = "DojoModel"
class_hash = "0x433f214aacb38f1a1ddb61fa2fc72881e9a1d3d4dcd70ec3216d9b9210efec4"
original_class_hash = "0x433f214aacb38f1a1ddb61fa2fc72881e9a1d3d4dcd70ec3216d9b9210efec4"
abi = "manifests/prod/abis/base/models/eternum_models_map_tile.json"
name = "eternum::models::map::tile"

[[members]]
name = "_col"
type = "u128"
key = true

[[members]]
name = "_row"
type = "u128"
key = true

[[members]]
name = "col"
type = "u128"
key = false

[[members]]
name = "row"
type = "u128"
key = false

[[members]]
name = "explored_by_id"
type = "u128"
key = false

[[members]]
name = "explored_at"
type = "u64"
key = false

[[members]]
name = "biome"
type = "Biome"
key = false
