kind = "DojoModel"
class_hash = "0x97b7528ea8fe495403d1f84cf3491c1462d7711dd5971bf454756efbccbe7"
original_class_hash = "0x97b7528ea8fe495403d1f84cf3491c1462d7711dd5971bf454756efbccbe7"
abi = "manifests/prod/abis/base/models/eternum_models_config_bank_config.json"
name = "eternum::models::config::bank_config"

[[members]]
name = "config_id"
type = "u128"
key = true

[[members]]
name = "lords_cost"
type = "u128"
key = false

[[members]]
name = "lp_fee_scaled"
type = "u128"
key = false
