kind = "DojoContract"
class_hash = "0x457276debceacbc9f006754f67d3b4e558b0495b6d0368a2ebe55dbf53c907b"
original_class_hash = "0x457276debceacbc9f006754f67d3b4e558b0495b6d0368a2ebe55dbf53c907b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_config_contracts_config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
