kind = "DojoContract"
class_hash = "0x68fbf72162aa8df4bb0306fbe2b4229c633d953220123ef4349b54d0c613826"
original_class_hash = "0x68fbf72162aa8df4bb0306fbe2b4229c633d953220123ef4349b54d0c613826"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_buildings_contracts_building_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::buildings::contracts::building_systems"
