kind = "DojoContract"
class_hash = "0x42bc862bc8767a1914e59d9e4e2be4c8338974736ad579155b092cad271da88"
original_class_hash = "0x42bc862bc8767a1914e59d9e4e2be4c8338974736ad579155b092cad271da88"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_combat_contracts_combat_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::combat::contracts::combat_systems"
