kind = "DojoContract"
class_hash = "0x562ad9ea74c01828d9b4a4da867ce608e0f860782398f4325eb2b7ee9add9fe"
original_class_hash = "0x562ad9ea74c01828d9b4a4da867ce608e0f860782398f4325eb2b7ee9add9fe"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::trade::contracts::trade_systems::trade_systems"
