kind = "DojoContract"
class_hash = "0xc73282c0be0e438ef1b3feee1b328203993fb67d485bd2a996dbe55971f5ce"
original_class_hash = "0xc73282c0be0e438ef1b3feee1b328203993fb67d485bd2a996dbe55971f5ce"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::test::contracts::resource::test_resource_systems"
