kind = "DojoContract"
class_hash = "0x5bb90d3558c9c12e709379e671d6acd542d249fe587946577ca286ac4b4829b"
original_class_hash = "0x5bb90d3558c9c12e709379e671d6acd542d249fe587946577ca286ac4b4829b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::test::contracts::resource::test_resource_systems"
