kind = "DojoContract"
class_hash = "0x7177805e2c26b87335cae45c0e91603bd6a0b958b90ddc2552d1313136ddbc6"
original_class_hash = "0x7177805e2c26b87335cae45c0e91603bd6a0b958b90ddc2552d1313136ddbc6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_buildings_contracts_building_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::buildings::contracts::building_systems"
