kind = "DojoContract"
class_hash = "0x37c757db5a6749bd412116754e0fdac45ab666e72fd19b1e54120f7f9544ce1"
original_class_hash = "0x37c757db5a6749bd412116754e0fdac45ab666e72fd19b1e54120f7f9544ce1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_leveling_contracts_leveling_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::leveling::contracts::leveling_systems"
