kind = "DojoContract"
class_hash = "0xee1518f39f065ce31c526a585de42a3729e834d896986e1674692a2dae6576"
original_class_hash = "0xee1518f39f065ce31c526a585de42a3729e834d896986e1674692a2dae6576"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_bank_contracts_bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems"
