kind = "DojoContract"
class_hash = "0x35d61bef9903ee519d71abb9c722ae203d14f9c06e6d216f643d98c8d723c34"
original_class_hash = "0x35d61bef9903ee519d71abb9c722ae203d14f9c06e6d216f643d98c8d723c34"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_realm_contracts_realm_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::realm::contracts::realm_systems"
