kind = "DojoContract"
class_hash = "0xf6c1b8e241e1f9c072d0a7302814b53dd8094b528e8ae29b388950b1678596"
original_class_hash = "0xf6c1b8e241e1f9c072d0a7302814b53dd8094b528e8ae29b388950b1678596"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::test::contracts::resource::test_resource_systems"
