kind = "DojoContract"
class_hash = "0x4c67ccddc97836bf7612206d7488118b77a787cb9f2a128717e0fe9da6f46f5"
original_class_hash = "0x4c67ccddc97836bf7612206d7488118b77a787cb9f2a128717e0fe9da6f46f5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_realm_contracts_realm_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::realm::contracts::realm_systems"
