kind = "DojoContract"
class_hash = "0x7f4039e886106ec392a1ed486d19bb3605cb4e6d6806fe6c1b74e384a701ae7"
original_class_hash = "0x7f4039e886106ec392a1ed486d19bb3605cb4e6d6806fe6c1b74e384a701ae7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_map_contracts_map_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::map::contracts::map_systems"
