kind = "DojoContract"
class_hash = "0x4a504a5fe710c9c2c786af272f6a6dc6f3fc0860c959a2dbd1a6dc5858fae3c"
original_class_hash = "0x4a504a5fe710c9c2c786af272f6a6dc6f3fc0860c959a2dbd1a6dc5858fae3c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_leveling_contracts_leveling_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::leveling::contracts::leveling_systems"
