kind = "DojoContract"
class_hash = "0x47db681898fb7527bf781dc5dfe37db50f87597303943043bab0fc92e9903e1"
original_class_hash = "0x47db681898fb7527bf781dc5dfe37db50f87597303943043bab0fc92e9903e1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_config_contracts_config_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::config::contracts::config_systems"
