kind = "DojoContract"
class_hash = "0x35f21156436ef5aa48428ee916e43cde9251889657c464bb6dcaf089d7ca128"
original_class_hash = "0x35f21156436ef5aa48428ee916e43cde9251889657c464bb6dcaf089d7ca128"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::transport::contracts::road_systems::road_systems"
