kind = "DojoContract"
class_hash = "0x2fff6d59e54bc3ab734ce5e52de1263b2e937a844000a2065dd2c3b87ad9057"
original_class_hash = "0x2fff6d59e54bc3ab734ce5e52de1263b2e937a844000a2065dd2c3b87ad9057"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_realm_contracts_realm_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::realm::contracts::realm_systems"
