kind = "DojoContract"
class_hash = "0x54adb0ce4e6b1bb6bd357f483fa48352a5b9f8885d2a340984bf4486dbb9e3f"
original_class_hash = "0x54adb0ce4e6b1bb6bd357f483fa48352a5b9f8885d2a340984bf4486dbb9e3f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::transport::contracts::road_systems::road_systems"
