kind = "DojoContract"
class_hash = "0xc928c142e210dbfd3333a5aaa1b2d39fec46dba0f2230f05d2873808c738dd"
original_class_hash = "0xc928c142e210dbfd3333a5aaa1b2d39fec46dba0f2230f05d2873808c738dd"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_resources_contracts_resource_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::resources::contracts::resource_systems"
