kind = "DojoContract"
class_hash = "0x617536ef15af78c0c25a859238d652d412b564811d461543fae4e9352439ddb"
original_class_hash = "0x617536ef15af78c0c25a859238d652d412b564811d461543fae4e9352439ddb"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_combat_contracts_combat_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::combat::contracts::combat_systems"
