kind = "DojoContract"
class_hash = "0x4a4eac453d4925c4914db00b1990aa0d8d419638ae278127c0e456978c5f155"
original_class_hash = "0x4a4eac453d4925c4914db00b1990aa0d8d419638ae278127c0e456978c5f155"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_bank_contracts_bank_systems_bank_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::bank::contracts::bank_systems::bank_systems"
