kind = "DojoContract"
class_hash = "0x7bbe9392c4be4b3992f57d5d81bf2d585024f91702f00c5138164112deb72f7"
original_class_hash = "0x7bbe9392c4be4b3992f57d5d81bf2d585024f91702f00c5138164112deb72f7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::test::contracts::resource::test_resource_systems"
