kind = "DojoContract"
class_hash = "0x643978f3a3961a59b55d0ea1b0a5790ef17d9ef3dc9cafdf82ef6ab4a79495c"
original_class_hash = "0x643978f3a3961a59b55d0ea1b0a5790ef17d9ef3dc9cafdf82ef6ab4a79495c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_buildings_contracts_building_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::buildings::contracts::building_systems"
