kind = "DojoContract"
class_hash = "0x5dc92bd5fafdcf873fc5b9089dd5e7137b0ef59b03b7e52371457e651ea5889"
original_class_hash = "0x5dc92bd5fafdcf873fc5b9089dd5e7137b0ef59b03b7e52371457e651ea5889"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_combat_contracts_combat_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::combat::contracts::combat_systems"
