kind = "DojoContract"
class_hash = "0x2c47a56df096c69054743f862c3983829cbe468910106e44b7b3fb1d4c51d22"
original_class_hash = "0x2c47a56df096c69054743f862c3983829cbe468910106e44b7b3fb1d4c51d22"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/eternum_systems_buildings_contracts_building_systems.json"
reads = []
writes = []
computed = []
name = "eternum::systems::buildings::contracts::building_systems"
